<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('Inventory Capital Report') }}</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { margin-bottom: 20px; border-bottom: 1px solid #ddd; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #333; }
        .header p { margin: 5px 0 0; color: #666; }
        .summary { margin-bottom: 20px; background-color: #f9fafb; padding: 15px; border-radius: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { padding: 8px 10px; border-bottom: 1px solid #eee; text-align: left; }
        th { background-color: #f3f4f6; font-weight: bold; color: #374151; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .total-row td { font-weight: bold; background-color: #f9fafb; border-top: 2px solid #ddd; }
        .badge { display: inline-block; padding: 2px 6px; border-radius: 10px; font-size: 10px; font-weight: bold; }
        .badge-green { background-color: #dcfce7; color: #166534; }
        .badge-yellow { background-color: #fef9c3; color: #854d0e; }
        .badge-red { background-color: #fee2e2; color: #991b1b; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ __('Inventory Capital Report') }}</h1>
        <p>{{ __('Date') }}: {{ now()->format('d M Y, H:i') }} | {{ __('Generated by') }}: {{ auth()->user()->name }}</p>
    </div>

    <div class="summary">
        <strong>{{ __('Total Inventory Capital') }}:</strong> 
        <span style="font-size: 16px; margin-left: 10px;">Rp {{ number_format($totalCapital, 0, ',', '.') }}</span>
        <br>
        <strong>{{ __('Total Products') }}:</strong> {{ $products->count() }}
        <br>
        <strong>{{ __('Total Items') }}:</strong> {{ $products->sum('stock') }}
    </div>

    <table>
        <thead>
            <tr>
                <th>{{ __('Product') }}</th>
                <th>{{ __('SKU') }}</th>
                <th class="text-right">{{ __('Cost') }}</th>
                <th class="text-center">{{ __('Stock') }}</th>
                <th class="text-right">{{ __('Capital Value') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $product)
                <tr>
                    <td>{{ $product->name }} <br> <small style="color: #666;">{{ $product->category->name ?? '-' }}</small></td>
                    <td>{{ $product->sku }}</td>
                    <td class="text-right">Rp {{ number_format($product->cost, 0, ',', '.') }}</td>
                    <td class="text-center">
                        {{ number_format($product->stock) }}
                    </td>
                    <td class="text-right">Rp {{ number_format($product->cost * $product->stock, 0, ',', '.') }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr class="total-row">
                <td colspan="3" class="text-right">{{ __('Total') }}</td>
                <td class="text-center">{{ number_format($products->sum('stock')) }}</td>
                <td class="text-right">Rp {{ number_format($totalCapital, 0, ',', '.') }}</td>
            </tr>
        </tfoot>
    </table>
</body>
</html>
