<?php

namespace App\Services;

use App\Models\Sale;
use App\Models\Transaction;
use Carbon\Carbon;
use Illuminate\Support\Collection;

class FinancialSyncService
{
    /**
     * Sync a sale to transaction table
     */
    public function syncSaleToTransaction(Sale $sale): Transaction
    {
        return Transaction::updateOrCreate(
            [
                'source_type' => 'sale',
                'source_id' => $sale->id,
            ],
            [
                'type' => 'income',
                'amount' => $sale->total_amount,
                'category' => 'Sales',
                'description' => "Sale #{$sale->invoice_number} - {$sale->customer?->name}",
                'date' => $sale->created_at->format('Y-m-d'),
                'reference_number' => $sale->invoice_number,
                'payment_method' => $this->mapPaymentMethod($sale->payment_method),
                'status' => $this->mapSaleStatusToTransaction($sale->status, $sale->payment_status),
                'user_id' => $sale->user_id,
                'customer_id' => $sale->customer_id,
                'tenant_id' => $sale->tenant_id,
            ]
        );
    }

    /**
     * Get unified financial report for a date range
     */
    public function getUnifiedReport(Carbon $startDate, Carbon $endDate): array
    {
        // Get all transactions in date range
        $transactions = Transaction::whereBetween('date', [$startDate, $endDate])
            ->where('status', 'completed')
            ->get();

        // Separate auto-generated vs manual transactions
        $autoGenerated = $transactions->whereNotNull('source_type');
        $manual = $transactions->whereNull('source_type');

        // Calculate totals
        $salesIncome = $autoGenerated->where('type', 'income')->sum('amount');
        $manualIncome = $manual->where('type', 'income')->sum('amount');
        $expenses = $manual->where('type', 'expense')->sum('amount');

        // Get breakdown by category
        $incomeByCategory = $manual->where('type', 'income')
            ->groupBy('category')
            ->map->sum('amount');

        $expensesByCategory = $manual->where('type', 'expense')
            ->groupBy('category')
            ->map->sum('amount');

        // Get payment method breakdown
        $paymentMethodBreakdown = $transactions
            ->groupBy('payment_method')
            ->map(function ($group) {
                return [
                    'income' => $group->where('type', 'income')->sum('amount'),
                    'expense' => $group->where('type', 'expense')->sum('amount'),
                ];
            });

        return [
            'period' => [
                'start' => $startDate->format('Y-m-d'),
                'end' => $endDate->format('Y-m-d'),
            ],
            'totals' => [
                'sales_income' => $salesIncome,
                'manual_income' => $manualIncome,
                'total_income' => $salesIncome + $manualIncome,
                'expenses' => $expenses,
                'net_profit' => ($salesIncome + $manualIncome) - $expenses,
            ],
            'breakdown' => [
                'income_by_category' => $incomeByCategory,
                'expenses_by_category' => $expensesByCategory,
                'payment_methods' => $paymentMethodBreakdown,
            ],
            'counts' => [
                'total_transactions' => $transactions->count(),
                'auto_generated' => $autoGenerated->count(),
                'manual' => $manual->count(),
            ],
        ];
    }

    /**
     * Get sales-only financial summary
     */
    public function getSalesFinancialSummary(Carbon $startDate, Carbon $endDate): array
    {
        $salesTransactions = Transaction::where('source_type', 'sale')
            ->whereBetween('date', [$startDate, $endDate])
            ->where('status', 'completed')
            ->get();

        return [
            'total_sales' => $salesTransactions->sum('amount'),
            'transaction_count' => $salesTransactions->count(),
            'average_sale' => $salesTransactions->avg('amount'),
            'payment_methods' => $salesTransactions->groupBy('payment_method')
                ->map->sum('amount'),
        ];
    }

    /**
     * Get manual transactions summary
     */
    public function getManualTransactionsSummary(Carbon $startDate, Carbon $endDate): array
    {
        $manualTransactions = Transaction::whereNull('source_type')
            ->whereBetween('date', [$startDate, $endDate])
            ->get();

        $income = $manualTransactions->where('type', 'income');
        $expenses = $manualTransactions->where('type', 'expense');

        return [
            'income' => [
                'total' => $income->sum('amount'),
                'count' => $income->count(),
                'by_category' => $income->groupBy('category')->map->sum('amount'),
            ],
            'expenses' => [
                'total' => $expenses->sum('amount'),
                'count' => $expenses->count(),
                'by_category' => $expenses->groupBy('category')->map->sum('amount'),
            ],
            'net_manual' => $income->sum('amount') - $expenses->sum('amount'),
        ];
    }

    /**
     * Sync all existing sales to transactions (for initial setup)
     */
    public function syncAllExistingSales(): array
    {
        $synced = 0;
        $failed = 0;

        Sale::where('status', 'completed')
            ->chunk(100, function ($sales) use (&$synced, &$failed) {
                foreach ($sales as $sale) {
                    try {
                        $this->syncSaleToTransaction($sale);
                        $synced++;
                    } catch (\Exception $e) {
                        $failed++;
                        // Log error: $e->getMessage()
                    }
                }
            });

        return [
            'synced' => $synced,
            'failed' => $failed,
            'total_processed' => $synced + $failed,
        ];
    }

    /**
     * Map sale payment method to transaction payment method
     */
    protected function mapPaymentMethod(string $paymentMethod): string
    {
        return match ($paymentMethod) {
            'cash' => 'Cash',
            'card' => 'Credit Card',
            'bank_transfer' => 'Bank Transfer',
            'qris' => 'QRIS',
            'ewallet' => 'E-Wallet',
            default => ucfirst($paymentMethod)
        };
    }

    /**
     * Map sale status to transaction status
     */
    protected function mapSaleStatusToTransaction(string $saleStatus, string $paymentStatus): string
    {
        return match (true) {
            $saleStatus === 'refunded' => 'cancelled',
            $paymentStatus === 'unpaid' => 'pending',
            $saleStatus === 'completed' && $paymentStatus === 'paid' => 'completed',
            default => 'pending'
        };
    }
}