<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\SoftDeletes;

class Transaction extends Model
{
    use HasFactory, HasUuids, SoftDeletes;

    protected $fillable = [
        'type',
        'amount',
        'category',
        'description',
        'date',
        'reference_number',
        'payment_method',
        'status',
        'source_type',
        'source_id',
        'user_id',
        'customer_id',
        'tenant_id',
    ];

    protected $casts = [
        'amount' => 'decimal:2',
        'date' => 'date',
    ];

    /**
     * Get the source model (polymorphic relationship)
     */
    public function source()
    {
        return $this->morphTo('source', 'source_type', 'source_id');
    }

    /**
     * Get the user who created this transaction
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the customer associated with this transaction
     */
    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    /**
     * Get the tenant associated with this transaction
     */
    public function tenant()
    {
        return $this->belongsTo(Tenant::class);
    }

    /**
     * Scope to get only manual transactions (not auto-generated)
     */
    public function scopeManual($query)
    {
        return $query->whereNull('source_type');
    }

    /**
     * Scope to get only auto-generated transactions
     */
    public function scopeAutoGenerated($query)
    {
        return $query->whereNotNull('source_type');
    }

    /**
     * Scope to get transactions by source type
     */
    public function scopeBySource($query, string $sourceType)
    {
        return $query->where('source_type', $sourceType);
    }

    /**
     * Check if this is a manual transaction
     */
    public function isManual(): bool
    {
        return is_null($this->source_type);
    }

    /**
     * Check if this is an auto-generated transaction
     */
    public function isAutoGenerated(): bool
    {
        return !is_null($this->source_type);
    }
}
